# Generated by Django 5.0.1 on 2024-03-09 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_apitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userinfo'),
        ),
    ]
